version: '3.1'

volumes:
  spring_docker:
  elasticsearch:

services:
  docker_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "spring_docker"
    volumes:
      - spring_docker:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    image: dzhambo05/example
    container_name: example
    ports:
      - "8080:8080"
    depends_on:
      - docker_db
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:postgresql://docker_db:5432/spring_docker",
              "spring.datasource.username" : "${DB_USERNAME}",
              "spring.datasource.password" : "${DB_PASSWORD}",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
      JAVA_OPTS: '-Xmx512m'